### ISSUE TITLE
week 01 回饋

### ISSUE THREAD

**Issue by azole** [Lean0411/git-practice#1]
讓我們透過這門課練習更具體、更深入的學習一個技術，

例如 `tree: 代表目錄結構，可以更好地了解整個檔案的結構`，什麼叫做「更好地了解整個檔案結構」？git 做了什麼（怎麼做）讓我們更好地了解？

以「紀錄在 git repo 操作過程中，.git 檔案夾裡的變化，看看你可以觀察到什麼？」這題來說，你紀錄的是 add remote 之後的變化，那 `git add`、`git commit`、`git branch`、`git switch` （或是 checkout） 之後的變化呢？做了這些操作後，跟 blob, tree, commit,... 等有什麼關係？這些物件又是存在 .git 檔案夾裡的哪裡？

你有多紀錄一些作業單以外提到的東西，這是很棒的，但除了操作外，我們試試看對技術有更深層的了解。

**Comment by Lean0411** [comment]
謝謝老師讓我有這個機會可以更深入了思考背後的原因，並做了一些的實驗解答出問題！

**Comment by azole** [comment]
所以你有再多做一些實驗了？那要分享看看嗎？簡單在這邊分享給我就好？

**Comment by Lean0411** [comment]
我有在YouTube 上看到一個影片：內容在介紹git物件,blob, tree, commit, tag物件的關係。

做的實驗有：
- 觀察HEAD在切換不同的分支他所指向的位置。
- 創建多個「內容相同」及「內容不同」的檔案，並觀察SHA的數值之間的關係，確定是否真的是用「內容」去做SHA的結果。
- 觀察commit和tree之間的關係，當時觀察到tree底下為什麼還有tree？（檔案夾的概念，檔案夾裡面有有可能會有檔案夾）並利用tree ID去看 tree底下又會有哪些關聯檔案。

這讓我詳細的了解git背後的意義，像是：
所有的blob物件都是透過「內容」來當作檔案名的，但為什麼要這樣做？ 這樣做一定有他的意義吧？ 
是因為在不同的地方找尋內容，效率是非常高的。（至於為什麼效率高就是有關作業系統、演算法、資料結構）

我也非常認同老師說的「歷史」、「作業系統」非常重要，「歷史」其背後的故事一定有他的意義，而且事實不可「被覆蓋」！但是有點疑惑的地方是，可能我沒接觸過「經濟學」但是為什麼老師會覺得這如此重要呢？（有點偏題了...）

**Comment by azole** [comment]
可以看看歷史，有多少歷史事件是因為經濟影響的，甚至可以說是經濟驅動了人類社會發展進而變成歷史

**Comment by azole** [comment]
對了，如果沒有其他要再跟我討論的部分，那這個 issue 可以 close 了。
